components:
  schemas:
    FactResponse:
      description: Random fact response model.
      properties:
        fact:
          description: Interesting fact
          title: Fact
          type: string
        source:
          anyOf:
          - type: string
          - type: 'null'
          description: Fact source
          title: Source
      required:
      - fact
      title: FactResponse
      type: object
    GenerateTextRequest:
      description: Text generation request model.
      properties:
        max_length:
          anyOf:
          - maximum: 500.0
            minimum: 1.0
            type: integer
          - type: 'null'
          default: 50
          description: Maximum length of generated text
          title: Max Length
        prompt:
          description: Text prompt for generation
          maxLength: 1000
          minLength: 1
          title: Prompt
          type: string
        temperature:
          anyOf:
          - maximum: 2.0
            minimum: 0.1
            type: number
          - type: 'null'
          default: 1.0
          description: Temperature for text generation
          title: Temperature
      required:
      - prompt
      title: GenerateTextRequest
      type: object
    GenerateTextResponse:
      description: Text generation response model.
      properties:
        generated_text:
          description: Generated text
          title: Generated Text
          type: string
        input_prompt:
          description: Original input prompt
          title: Input Prompt
          type: string
        metadata:
          additionalProperties: true
          description: Additional metadata
          title: Metadata
          type: object
      required:
      - generated_text
      - input_prompt
      title: GenerateTextResponse
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    HealthResponse:
      description: Health check response model.
      properties:
        status:
          description: Application status
          title: Status
          type: string
        timestamp:
          description: Timestamp of the health check
          format: date-time
          title: Timestamp
          type: string
        version:
          description: Application version
          title: Version
          type: string
      required:
      - status
      - timestamp
      - version
      title: HealthResponse
      type: object
    QuoteResponse:
      description: Random quote response model.
      properties:
        author:
          description: Quote author
          title: Author
          type: string
        category:
          anyOf:
          - type: string
          - type: 'null'
          description: Quote category
          title: Category
        quote:
          description: Quote text
          title: Quote
          type: string
      required:
      - quote
      - author
      title: QuoteResponse
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
    WeatherRequest:
      description: Weather request model.
      properties:
        city:
          description: City name
          maxLength: 100
          minLength: 1
          title: City
          type: string
        country_code:
          anyOf:
          - maxLength: 2
            minLength: 2
            type: string
          - type: 'null'
          description: ISO 3166 country code
          title: Country Code
      required:
      - city
      title: WeatherRequest
      type: object
    WeatherResponse:
      description: Weather response model.
      properties:
        city:
          description: City name
          title: City
          type: string
        country:
          description: Country name
          title: Country
          type: string
        description:
          description: Weather description
          title: Description
          type: string
        humidity:
          anyOf:
          - type: integer
          - type: 'null'
          description: Humidity percentage
          title: Humidity
        temperature:
          description: Temperature in Celsius
          title: Temperature
          type: number
        wind_speed:
          anyOf:
          - type: number
          - type: 'null'
          description: Wind speed in m/s
          title: Wind Speed
      required:
      - city
      - country
      - temperature
      - description
      title: WeatherResponse
      type: object
info:
  description: A scalable FastAPI application with auto-generated documentation and
    client type generation
  title: Scalable FastAPI Application
  version: 1.0.0
  x-logo:
    url: https://fastapi.tiangolo.com/img/logo-margin/logo-teal.png
openapi: 3.1.0
paths:
  /:
    get:
      description: APIドキュメントリンク付きのルートエンドポイント。
      operationId: root__get
      responses:
        '200':
          content:
            text/html:
              schema:
                type: string
          description: Successful Response
      summary: Root
  /api/v1/external/fact:
    get:
      description: 'ランダムな興味深い豆知識を取得します。


        ランダムな教育的事実を返します。'
      operationId: get_random_fact_api_v1_external_fact_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FactResponse'
          description: Successful Response
      summary: Get Random Fact
      tags:
      - external
  /api/v1/external/joke:
    get:
      description: 'ランダムなプログラミングジョークを取得します。


        ランダムなプログラミング関連のジョークを返します。'
      operationId: get_random_joke_api_v1_external_joke_get
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: true
                title: Response Get Random Joke Api V1 External Joke Get
                type: object
          description: Successful Response
      summary: Get Random Joke
      tags:
      - external
  /api/v1/external/quote:
    get:
      description: 'ランダムな名言を取得します。


        厳選されたコレクションからランダムな名言を返します。'
      operationId: get_random_quote_api_v1_external_quote_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteResponse'
          description: Successful Response
      summary: Get Random Quote
      tags:
      - external
  /api/v1/external/weather:
    post:
      description: '都市の天気情報を取得します。


        現在の環境では外部APIアクセスが制限される可能性があるため、

        このエンドポイントはモック天気データを提供します。'
      operationId: get_weather_api_v1_external_weather_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeatherRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Weather
      tags:
      - external
  /api/v1/health/:
    get:
      description: 'ヘルスチェックエンドポイント


        アプリケーションの現在の状態を返します。'
      operationId: health_check_api_v1_health__get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
          description: Successful Response
      summary: Health Check
      tags:
      - health
  /api/v1/health/detailed:
    get:
      description: '詳細ヘルスチェックエンドポイント


        アプリケーションの状態に関する詳細情報を返します。'
      operationId: detailed_health_check_api_v1_health_detailed_get
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: true
                title: Response Detailed Health Check Api V1 Health Detailed Get
                type: object
          description: Successful Response
      summary: Detailed Health Check
      tags:
      - health
  /api/v1/text/echo:
    post:
      description: '入力テキストをメタデータ付きでエコーバックします。


        処理情報と共に入力を返すシンプルなエンドポイントです。'
      operationId: echo_text_api_v1_text_echo_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateTextRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: true
                title: Response Echo Text Api V1 Text Echo Post
                type: object
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Echo Text
      tags:
      - text
  /api/v1/text/generate:
    post:
      description: '入力プロンプトに基づいてテキストを生成します。


        外部モデルアクセスが利用できないため、このエンドポイントでは

        シンプルなルールベースアプローチを使用してテキストを生成します。'
      operationId: generate_text_api_v1_text_generate_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateTextRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateTextResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Generate Text
      tags:
      - text
  /generate:
    post:
      description: '元の/generateエンドポイント（後方互換性のため）


        この機能は /api/v1/text/generate に移行されましたが、

        既存のクライアントとの互換性を保つために提供されています。'
      operationId: generate_text_legacy_generate_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateTextRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateTextResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Generate Text Legacy
servers:
- description: 開発サーバー
  url: http://localhost:8000
- description: 本番サーバー
  url: https://api.example.com
